name: pr-check

on: [pull_request]

jobs:
  unit-tests:
    name: run unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.24

      - name: run tests
        run: go test ./...

      - name: run coverage tests
        run: go test -coverprofile=coverage.txt ./...

      - name: build tesh
        run: go build -o tesh main.go

      - name: run scripts smoke tests
        run: ./scripts/smoke-run.sh

      - name: run scenarios smoke tests
        run: ./scripts/smoke-scenarios.sh

      - name: run files smoke tests
        run: ./scripts/smoke-files.sh

      - name: run scenarios with expectations smoke tests
        run: ./scripts/smoke-expects.sh

      - name: run scenarios with calls expectations smoke tests
        run: ./scripts/smoke-calls.sh

      - name: run coverage on scripts
        run: ./tesh examples/ex7/ex7.sh --coverage=examples/ex7/coverage.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}