name: pr-check

on: [pull_request]

jobs:
  unit-tests:
    name: run unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.24

      - name: run tests
        run: go test ./...

      - name: build tesh
        run: go build -o tesh main.go

      - name: run scripts smoke tests
        run: |
          # should exit with code != 0
          ! ./tesh examples/ex1.sh
          # should print "the file /path/to/file does not exist" in the standard error
          ./tesh examples/ex1.sh 2>&1 > /dev/null | grep "cat: /path/to/file: No such file or directory"

      - name: run scenarios smoke tests
        run: |
          # should exit with code 0
          ./tesh examples/ex1.sh examples/ex1.yaml file-exists
          # should print "some text in the file" in the standard output
          ./tesh examples/ex1.sh examples/ex1.yaml file-exists | grep "some text in the file"
          # should exit with code != 0
          ! ./tesh examples/ex1.sh examples/ex1.yaml file-not-exists
          # should print "the file /path/to/file does not exist" in the standard error
          ./tesh examples/ex1.sh examples/ex1.yaml file-not-exists 2>&1 > /dev/null | grep "the file /path/to/file does not exist"
